# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Build and test Spring boot application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:


  compile:
    runs-on: ubuntu-latest
    name: Running Java

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven

  test:
    runs-on: ubuntu-latest
    name: Build with Maven
    needs: compile
    steps:
      - uses: actions/checkout@v3
      - name: Add secrets to tests
      run: printf ${{secrets.SPRING_DATASOURCE_PASSWORD}} >> src/main/resources/application.properties
      shell: bash

        - name: install maven
          run: mvn clean install
        - name: Test with Maven
          run: mvn -B test
